Attribute VB_Name = "Module1"
Global GotoFloor As Integer
Global CurrentFloor As Integer
Global CurrentFloorExact As Single
Global DistanceToTravel As Single
Global Destination As Single
Global OriginalLocation As Single
Global StoppingDistance As Single
Global FineTune As Boolean
